### ISSUE TITLE
Use random messages

### ISSUE THREAD

**Issue by prichrd** [joelchartier/slackbot-pomodoro#17]
I think a good improvement to make the bot look a little bit more human, would be to have different answers to some queries. So let's say you start a pomodoro, the bot could randomly answer from this set of answers (These are just examples, I know they are bad):
- `Aww yes, I started your pomodoro`
- `Your next XX minutes will be so productive that you might loose track of time`
- `See you in XX minutes!`

**Comment by pric** [comment]
This should be thinked about before #14
